travis:
  secure:
    BINSTAR_TOKEN: F4Fy+ghDcwCQYxQ4whWloPZ/M9WMqmBNyULxSMR+oMvtun+S1DqBMaDU7mgBh/BTRPn11Na/R0r8TMjBh2r4wj+sqAwH96zPVVFKeymeVHDGqMk+iJDVKdZ3s6jDYoGHQ09ondabn2Kp7Iuyc74v7raafqF5EoMZvD6xF/zTeuGuOHSMJv8aLhhw1tepl4s+CMlbPFyaAEEAo7qnhOkVChQDrjRm35DB+Xb+2IcEnt6UBFeI/cS7gITS4w0IXqFOBxWviGzTIaIOJO/aANuO4J8rvXhfmB+Xww8haS0bn98503QkOa/63spzsqGyLCD0CqMyOx+t14xb+c+KJyE6MAn+9OCR4CIb7q7G5IRC5hMMUeq6qZIkkWjc+yckEO6RcOski+MjV2VwV6cReMY8tEfruHKlztOAUyl73iI1diGyhvIqKH9CNpQFL2j+3OUiGNdrynd50/Sr4eLqwkHMww0VOUBTn+Ibf2e1g5BkO0D5NlurXFA/fGSt/E6FyGFnv3eTFJFZLLw2sKpJMK9ESF41jGfM0LcsaC3SdrUFOeCPj5nt6dnQIS+azWk4jthHtp8RCNNvpVfesI0r37ACKPDZHIZpuPVm9daHXd4ZqwiYvHZm4XiTSs2cPLKFh23DDiZYCcO/wVuAqZ2riR2mB9dM/wA/qcBoG+z4ovCrADc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
