travis:
  secure:
    BINSTAR_TOKEN: OkH+Dkst7BuDn5btr3nyHOZHmHwsRjm22c4016qXNibFNE63w9uGz4f+730Gddql9ausUm2KPEbTdjlJ4GyUuMtst8TKxnGaGHVohdBKE2xMiOWwr0uSWwB3RIVCzBTU4w/P/Xx6o7uWuQHWwy5Y5f8vWzd6C30OcbJ+kbMRJ1YVsQ9aQm4zPtbaI4VuIiVZtXuKRchhgp7W5EdZ61PxuU+o4YAQYhN/xPdTyhyF1KikjndH5Mt7HgSRj+E8ydxRehuZx1jnBhstgUYLB/yDZri92tqTCzTeYqypGKSHBoKRnGi0qrt611uRnpzgKXDrMAni3KlcYf028Wj8R3ZEcpLw8x7wRIt/VhnOjkvjDV4kX1PX1eqIH3swOhzIKNJozBoxXR1jPc1vufjuRT87wjs907fce5sEsz/2vzpRDVw0ccygbzBjnhlWX03tsvMTeheVgmOfd2idq53oQej0T9RtJ5zOCGG3M8bXiQgSAiiXnKaXc3Ui6ONmBhzGK8MKkagYll1PUzdctKU/ku5fldOmzQM7lpi0r99iLZjeGL7Bp2JyjQxYRsypsrbsLlX+I4RzDhwnhjtBfDNxm6cuc9tJFRN343k+9nVrPpPe8ThCIyqLQOFBFn0MJ0WL3vPj8CuO9a/KpsKcOKB7C9bqdGpkUAIoFkNui4fKXxDfke0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
